name: Build

on:
  push:
    branches:
      - master
    paths-ignore:
      - README.md
      - .gitignore
      - .github/**
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - id: auth
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        token_format: access_token
        workload_identity_provider: ${{ secrets.GOOGLE_WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}

    - name: Login to Artifact Registry
      uses: docker/login-action@v1
      with:
        registry: us-west1-docker.pkg.dev
        username: oauth2accesstoken
        password: ${{ steps.auth.outputs.access_token }}

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: us-west1-docker.pkg.dev/zkpool-web/zkpool/taiko-prover-worker
        tags: |
          type=sha,prefix=build-,format=short
          type=raw,value=latest

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        platforms: linux/amd64
        cache-from: type=gha
        cache-to: type=gha
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}